apiVersion: apps/v1
kind: Deployment
metadata:
  name: atenet-router
  namespace: ate-system
spec:
  template:
    spec:
      containers:
      - name: envoy
        command:
        - /usr/local/bin/envoy
        - -c
        - /etc/envoy/envoy.yaml
        - --concurrency
        - "${ENVOY_CONCURRENCY}"
        resources:
          requests:
            cpu: "${ENVOY_CONCURRENCY}"
          limits:
            cpu: "${ENVOY_CONCURRENCY}"
      - name: atenet-router
        env:
        - name: GOMAXPROCS
          value: "${ROUTER_GOMAXPROCS}"
        - name: GOGC
          value: "${ROUTER_GOGC}"
        - name: GOMEMLIMIT
          value: "${ROUTER_GOMEMLIMIT_MIB}MiB"
        - name: ATE_ENABLE_PPROF
          value: "true"
        envFrom:
        - configMapRef:
            name: atenet-router-features
            optional: true
        resources:
          requests:
            cpu: "${ENVOY_CONCURRENCY}"
          limits:
            cpu: "${ENVOY_CONCURRENCY}"
